// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbXztHeBU6zXMF5HyoGFiAeQ4dhnnxiIs',
    appId: '1:884756195847:web:80a966c0faaec114b258a2',
    messagingSenderId: '884756195847',
    projectId: 'pratique1-2e129',
    authDomain: 'pratique1-2e129.firebaseapp.com',
    storageBucket: 'pratique1-2e129.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxG8eAFpxOQbrcrE40Qvru5vT6W5So5_w',
    appId: '1:884756195847:android:e2ea094e8e8ed9a0b258a2',
    messagingSenderId: '884756195847',
    projectId: 'pratique1-2e129',
    storageBucket: 'pratique1-2e129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1i7Cmh-Yz3b3uQoM6QJvl192nBefhru8',
    appId: '1:884756195847:ios:50d0830a31674276b258a2',
    messagingSenderId: '884756195847',
    projectId: 'pratique1-2e129',
    storageBucket: 'pratique1-2e129.appspot.com',
    iosClientId: '884756195847-431mh65ri83tm7hs6a72e319gel5tp53.apps.googleusercontent.com',
    iosBundleId: 'com.example.pratique1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1i7Cmh-Yz3b3uQoM6QJvl192nBefhru8',
    appId: '1:884756195847:ios:50d0830a31674276b258a2',
    messagingSenderId: '884756195847',
    projectId: 'pratique1-2e129',
    storageBucket: 'pratique1-2e129.appspot.com',
    iosClientId: '884756195847-431mh65ri83tm7hs6a72e319gel5tp53.apps.googleusercontent.com',
    iosBundleId: 'com.example.pratique1',
  );
}
